name: Lint Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Adjust to the version your project uses

      - name: Install dependencies
        run: npm install

      - name: Run linting
        run: npm run lint  # Adjust this command if your lint script is different

      - name: Check linting results
        run: |
          if grep -q 'error' <(npm run lint); then
            echo "Linting errors found. Exiting."
            exit 1
          else
            echo "No linting errors found."
          fi
